import Foundation

enum TerminalLauncherError: LocalizedError {
  case codexMissing
  case unsafeExistingFile

  var errorDescription: String? {
    switch self {
    case .codexMissing: return "Codex CLI could not be found."
    case .unsafeExistingFile: return "A different file already exists at the launcher path."
    }
  }
}

enum TerminalLauncherService {
  private static let marker = "# Generated by Codex Usage Tracker"

  static func slug(for name: String) -> String {
    let allowed = name.lowercased().map { character -> Character in
      character.isLetter || character.isNumber ? character : "-"
    }
    let slug = String(allowed)
      .split(separator: "-")
      .filter { !$0.isEmpty }
      .joined(separator: "-")
    return slug.isEmpty ? "profile" : slug
  }

  static func launcherURL(for profile: CodexProfile) -> URL {
    FileManager.default.homeDirectoryForCurrentUser
      .appendingPathComponent(".local/bin", isDirectory: true)
      .appendingPathComponent("codex-\(slug(for: profile.name))")
  }

  static func isInstalled(for profile: CodexProfile) -> Bool {
    guard let content = try? String(contentsOf: launcherURL(for: profile), encoding: .utf8) else {
      return false
    }
    return content.contains(marker)
  }

  static func install(for profile: CodexProfile) throws -> URL {
    guard let codex = CodexAppServerClient.resolveCodexExecutable() else {
      throw TerminalLauncherError.codexMissing
    }
    let url = launcherURL(for: profile)
    if FileManager.default.fileExists(atPath: url.path), !isInstalled(for: profile) {
      throw TerminalLauncherError.unsafeExistingFile
    }
    try FileManager.default.createDirectory(
      at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
    let home =
      profile.codexHome
      ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".codex").path
    let script = """
      #!/bin/sh
      \(marker)
      export CODEX_HOME=\(shellQuote((home as NSString).expandingTildeInPath))
      exec \(shellQuote(codex.path)) "$@"

      """
    try script.write(to: url, atomically: true, encoding: .utf8)
    try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    return url
  }

  static func uninstall(for profile: CodexProfile) throws {
    let url = launcherURL(for: profile)
    guard FileManager.default.fileExists(atPath: url.path) else { return }
    guard isInstalled(for: profile) else { throw TerminalLauncherError.unsafeExistingFile }
    try FileManager.default.removeItem(at: url)
  }

  private static func shellQuote(_ value: String) -> String {
    "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
  }
}
