import Foundation

enum TerminalLauncherError: LocalizedError, Equatable {
  case codexMissing
  case unsafeExistingFile

  var errorDescription: String? {
    switch self {
    case .codexMissing: return "Codex CLI could not be found."
    case .unsafeExistingFile: return "A different file already exists at the launcher path."
    }
  }
}

enum TerminalLauncherService {
  static func slug(for name: String) -> String {
    let allowed = name.lowercased().map { character -> Character in
      character.isLetter || character.isNumber ? character : "-"
    }
    let slug = String(allowed)
      .split(separator: "-")
      .filter { !$0.isEmpty }
      .joined(separator: "-")
    return slug.isEmpty ? "profile" : slug
  }

  static func launcherURL(for profile: CodexProfile, baseDirectory: URL? = nil) -> URL {
    let directory =
      baseDirectory
      ?? FileManager.default.homeDirectoryForCurrentUser
      .appendingPathComponent(".local/bin", isDirectory: true)
    if let existing = ownedLauncherURLs(for: profile, in: directory).first { return existing }
    let discriminator = profile.id.uuidString.prefix(8).lowercased()
    return directory.appendingPathComponent(
      "codex-\(slug(for: profile.name))-\(discriminator)")
  }

  static func isInstalled(for profile: CodexProfile, baseDirectory: URL? = nil) -> Bool {
    guard
      let content = try? String(
        contentsOf: launcherURL(for: profile, baseDirectory: baseDirectory), encoding: .utf8)
    else {
      return false
    }
    return content.contains(marker(for: profile))
  }

  static func install(
    for profile: CodexProfile,
    baseDirectory: URL? = nil,
    executableURL: URL? = nil
  ) throws -> URL {
    guard let codex = executableURL ?? CodexAppServerClient.resolveCodexExecutable() else {
      throw TerminalLauncherError.codexMissing
    }
    let url = launcherURL(for: profile, baseDirectory: baseDirectory)
    if FileManager.default.fileExists(atPath: url.path),
      !isInstalled(for: profile, baseDirectory: baseDirectory)
    {
      throw TerminalLauncherError.unsafeExistingFile
    }
    try FileManager.default.createDirectory(
      at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
    let home =
      profile.codexHome
      ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".codex").path
    let script = """
      #!/bin/sh
      \(marker(for: profile))
      export CODEX_HOME=\(shellQuote((home as NSString).expandingTildeInPath))
      exec \(shellQuote(codex.path)) "$@"

      """
    try script.write(to: url, atomically: true, encoding: .utf8)
    try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    return url
  }

  static func uninstall(for profile: CodexProfile, baseDirectory: URL? = nil) throws {
    let url = launcherURL(for: profile, baseDirectory: baseDirectory)
    guard FileManager.default.fileExists(atPath: url.path) else { return }
    guard isInstalled(for: profile, baseDirectory: baseDirectory) else {
      throw TerminalLauncherError.unsafeExistingFile
    }
    try FileManager.default.removeItem(at: url)
  }

  private static func marker(for profile: CodexProfile) -> String {
    "# Generated by Codex Usage Tracker for profile \(profile.id.uuidString)"
  }

  private static func ownedLauncherURLs(for profile: CodexProfile, in directory: URL) -> [URL] {
    guard
      let candidates = try? FileManager.default.contentsOfDirectory(
        at: directory, includingPropertiesForKeys: [.isRegularFileKey])
    else { return [] }
    return candidates.filter { url in
      guard url.lastPathComponent.hasPrefix("codex-"),
        let content = try? String(contentsOf: url, encoding: .utf8)
      else { return false }
      return content.contains(marker(for: profile))
    }
  }

  private static func shellQuote(_ value: String) -> String {
    "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
  }
}
